### ISSUE TITLE
Can't run heroku run rake db:reset

### ISSUE THREAD

**Issue by bao-qian** [jtreanor/SummerCourses#40]
``` bash
rake aborted!
Mysql2::Error: Lost connection to MySQL server during query: SELECT  `admin_users`.* FROM `admin_users`  WHERE `admin_users`.`reset_password_token` = 'm4GZHwrEq2pc8BzPmLx6' LIMIT 1
/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:243:in `query'
/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:243:in `block in execute'
```

**Comment by jtreanor** [comment]
I am not getting this error. Is it still a problem for you?

**Comment by bao-qian** [comment]
I also not getting this error now, may be our mysql server getting some problem last night.
If the problem will not occur today, I will close this issue.
